### ISSUE TITLE
Setup an "ingest" flow to export user restrictions data for US_MO and US_ID

### ISSUE THREAD

**Issue by daschi** [Recidiviz/pulse-dashboard#1033]
**Is your feature request related to a problem? Please describe.**
We will need to set up access control on the UP dashboard (including Lantern) based on the supervision locations that a user has access to. We currently have something setup for US_MO's restricted access view where they provide us a raw file to ingest, and then we transform that file and export the results to a table in the `reference_views` schema. This view is exported to the `recidiviz-{env}-dashboard-data` bucket as `supervision_location_restricted_access_emails.json`. We will need to also export this file for US_ID, US_ND, and US_PA. 

**Describe the solution you'd like**
The process for getting a list of user emails and the supervision locations they can access may change once we implement SSO connections. Because of that, we need a lightweight solution that will work in the interim. Details TBD/coming soon.

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by jovergaag** [comment]
From Julia:
Plan of action should be:
1. Figure out if we have this information already in one of the us_nd_raw_data tables. If we do, skip to step #3
2. If not ^, get in touch with US_ND (through Zak) to have them start sending us a table with the info we need.
3. Get that table set up so that we start producing a …_latest view for it (ask Anna about this process)
4. Modify the supervision_location_restricted_access_emails view to pull from this new …_latest view

**Comment by daschi** [comment]
@jovergaag I agree - I think it would be more straightforward to have this data sent to us specifically, and @sychang mentioned that we can try to request the schema we would like. We're already doing this for US_MO, although we didn't specify a schema so we may need to go back to them to get that updated. I don't think we should depend on the other ingest data to deduce a user's access level. Also once we have SSO setup, I think the ideal situation would be that the SSO Identity Provider would give us this data, and whatever we ingest at this point should match their internal IdP access levels.  

Also, I would confirm with Serena about US_ND - I'm not sure they will need access control before other states (i.e. US_ID, US_MO for vitals)

**Comment by jovergaag** [comment]
@daschi That makes sense. So maybe the first step is to start with US_MO and just adjust the schema for the table that they are already sending us before we add another state so that we are always dealing with one single schema. Then request the data from US_ID.

Did you intend for this issue to be the actual work of doing this? I was under the impression it was only for investigating and coming up with a plan, but am happy to attempt to do the work if that was your intention.

**Comment by daschi** [comment]
Yeah I intended this issue to be the work for setting up that process. Now that there's been more investigation though, do you think this should be broken out into more tasks? Maybe we can chat sometime today about it?

**Comment by jovergaag** [comment]
I think there should be 4 tasks.
1. Request the new schema from US_MO (that can be this issue)
2. Pull the new schema through calc into the the view such that the dashboard view has the new schema
3. Update the FE to use the new schema (maybe this is a good time to swap over to use the new bucket)
4. Request the data from US_ID

Now, that means that we're not getting the data from US_ID for at least a few weeks, so it depends on how quickly we need this. We can request it from US_MO simultaneously, but it doesn't give us any leeway if we discover that we're missing something important, we would have to change the ask to US_ID.

If we're confident in the schema, this issue can be to request the data in the new schema from both US_MO and US_ID.

**Comment by daschi** [comment]
Ok sounds good - let's start with US_MO for now since that's the current requirement, unless @sychang you think we need to get started on access control for US_ID sooner rather than later?

I'll create new tickets for number 2 & 3. I assume we'll also need another ticket to cleanup the old schema once the frontend is updated, [I have this ticket ](https://github.com/Recidiviz/recidiviz-data/issues/7278)which is about removing the restrictions file export to the lantern `dashboard-data` bucket, it could also include removing the old schema for that file.
