### ISSUE TITLE
MO violation bubble chart methodology is missing!

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#1044]
**What needs to be done? Why does it need to be done?**
When clicking "Additional info" For the violation history bubble chart, the methodology appears to have disappeared (all other charts are fine):

Methodology is for that section is here: https://docs.google.com/document/d/1q06zsWlTK3O4sqykPQQ4NQixScQyvjbqsFViH1GXfVQ/edit?ts=602b434c#heading=h.y54mfctqhz8n

**Additional context**
Not dire, but would prioritize for 4/26 since MO trainings kicking off. cc @Catacola

**Comment by jessex** [comment]
Just saw this and wanted to drive by with a quick thought: I _think_ this is because `us_mo_translations.ts` includes the line:
```
revocationsMatrixChartId: "admissionsMatrix",
```

But `us_mo_methodology.ts` has a key of `revocationMatrix` instead of `admissionsMatrix`. I didn't actually test it locally because my computer is perpetually panicking these days, but I'm guessing that's the cause? Change that key from the former to the latter and it should work.

**Comment by daschi** [comment]
This is deployed in staging and production now.
