### ISSUE TITLE
[Vitals][US_ID] Ingest ID data from backend

### ISSUE THREAD

**Issue by Catacola** [Recidiviz/pulse-dashboard#1111]
Set up the node backend to fetch and cache the ID vitals data from GCS.

The proposed data structure will be the same as the vitals for ND but the summary table will have different keys. For example, instead of having the keys `timely_discharge`, `timely_risk_assessment`, and `timely_contact`, the ID table will have the keys ~`employment`~, `timely_downgrade`, `timely_risk_assessment`, and `timely_contact`. (Key names are open to debate). They values in the `metric` column of the vitals time series view will also change accordingly for ID.

On the backend, this will likely be accomplished by having a separate summary view for ID and ND (and eventually for each state)

**Comment by jovergaag** [comment]
@Catacola My initial thoughts on this are that we should add these metrics to the existing view and just modify the metrics that are shown on the FE by tenant. Creating a separate view and trying to keep all of the summaries and time_series views (per state) in sync if and when we make changes to the schema because of a new feature on the FE sounds very error prone since they will all have mostly identical columns, but just one or two different metric columns. Imagine, if we want to change how the entity name is formatted, if we have 15 states and 15 views that all require the same formatting change, it could be a mess.

It seems like there are a limited and discrete number of metrics that we will be reporting on, so the number of columns in this view won't grow out of control.

Thoughts on this?

**Comment by Catacola** [comment]
If we build the queries on the backend via templates, it should be easy to keep them in sync with updates. However, I do see your point that the metrics shouldn't be that wide-ranging given our current proposals for states. If this does become an issue, we can come back and split later. I'll add `supervision_match` to the existing table.

**Comment by jovergaag** [comment]
We need to also add `entity_email_address` which can come from either `case_triage.etl_officers` (most likely) or `static_reference_tables.us_id_roster`. This is for the read-only Case Triage link.

**Comment by Catacola** [comment]
Update: to match the theme of the other fields, I called the new field `timely_downgrade`.

**Comment by Catacola** [comment]
https://github.com/Recidiviz/recidiviz-data/pull/8388
