### ISSUE TITLE
Role based redirect

### ISSUE THREAD

**Issue by jovergaag** [Recidiviz/pulse-dashboard#1154]
**Is your feature request related to a problem? Please describe.**
Now that we have launched Population Projections for US_ID and will soon be launching Vitals, we will need a way to redirect users to Case Triage if they are not leadership users. The Cosmos team will also do the work to redirect users to the Leadership Dashboard if a user tries to log in to Case Triage but is not in a leadership role.

The Cosmos team is taking on part of the work, and we are taking on part of the work to expedite this feature! Talk to Nikhil if you have questions about the Cosmos tasks which are:
- consolidate the Case Traige and Dashboard Auth- applications into a single application
- add the whitelist of Case Triage users into the postgres table
- update the Case Triage FE to check the role and redirect to the Leadership Dashboard if needed

cc: @nbhargava 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by cawarren** [comment]
This came up / was a topic of conversation in the cross-UP sync today, and I took an AI to try to drive it to ground on this EPIC instead of further discussion in-meeting.

cc @nbhargava @Catacola @soniachokshi @agronomic @annaliseirby @sychang 

_Note: All of the below are quick, hopefully-simplifying approaches for the issues described. If there are already in-flight solutions, or you have additional ideas or concerns about the below, toss them in here and let's discuss / quickly come to resolution._

Reading through these issues, it seems like there are two edge-cases to clarify:

1. If the user is _not_ authorized for the leadership tool, and is _also not_ authorized for Case Triage, how do we ensure they don't end up in a redirect loop?
2. If the user _is authorized for both tools_ a) how do we choose which to send them to initially, and b) how do we ensure they know how to get to the other one?

For 1, one option may be including a URL param when redirected, e.g. ?from=case_triage or ?from=vitals, and having the redirect logic check for that URL param. If found, that means we're about to redirect them right back to where they just came from, and we should instead give them an HTTP 401: Unauthorized. (Very open to simpler alternatives if available, this is off the cuff) There are wonky but pretty unlikely edge-cases here, but they seem mostly self-healing (e.g., they bookmark that redirect URL on Vitals, then get demoted to PO and lose access to Vitals, but when they try to navigate there it 401s instead of redirecting them - but that still seems reasonably-expected as behavior.)

For 2a, this is a non-issue in a 2-URL world (which is our current target). We simply take them to whichever URL they're trying to navigate to. In a 1-URL world, where they're heading only to app.recidiviz.org (no URL subdirectory) I'd propose we simply default to Vitals - but this may be moot for MVP.

For 2b, on the **Vitals** side I suggest we reuse the banner notification element in this scenario — if we detect the user is authorized for both apps, and lands in Vitals, have the banner notification display the message: "To manage your caseload, visit [Case Triage](#)."

For 2b, on the **Case Triage** side I suggest we reuse any current error message elements (butter bars, banners, etc.) to do the same, but with the following message: "To view organization metrics, visit [Vitals](#)."

**Comment by nbhargava** [comment]
For 1 -- we can actually tell from within each app whether they're authorized for the other one. So I think our logic is simplified to: "if you're not authorized for this app but are authorized for the other one, redirect. Else stay put"

**Comment by Catacola** [comment]
Even more simply, if they aren't authorized for either, we just display our standard  "Opps, something is wrong. Contact your admin" page.

**Comment by cawarren** [comment]
+1, sounds perfect.

**Comment by cawarren** [comment]
@nbhargava @Catacola Any thoughts on 2? Do you already have a plan in place (in which case no need for it), or if not does this seem like a simple / low-effort approach or does something else make more sense?

**Comment by nbhargava** [comment]
My understanding was that @agronomic and/or @soniachokshi were thinking about where in the UI we'd provide an account switcher. Once the designs are finalized, I'd imagine it to be pretty straightforward.

**Comment by Catacola** [comment]
On top of what Nikhil said, we will also have a unique interstitial page that will let the user select whether they want to go to leadership or case triage tools when they log in if they have access to both tools.
