### ISSUE TITLE
Add a loading spinner for Practices page

### ISSUE THREAD

**Issue by soniachokshi** [Recidiviz/pulse-dashboard#1220]
**What needs to be done? Why does it need to be done?**
For the Practices page, a loading spinner will show while the page is loading (instead of the current blank state). 

![loading state.png](https://images.zenhubusercontent.com/5f20518de59ddb3bd53d57b9/57d57474-252b-44b4-bd78-5b4b768609fe)  

Here's the mock in Figma: https://www.figma.com/file/H08AQJSaAIRxfeMP4iCUPh/UP-MVP?node-id=3486%3A2

**Additional context**
Add any other context about the task here.

**Comment by jovergaag** [comment]
The loading spinner is not appearing on the Vitals page for IE11. I had thought it is because we don't have a loading spinner on that page, but we actually do. The page is very slow to load and we see a loading spinner momentarily, but then the page (except for the header and IE11 banner) goes blank. After some investigation it seems like the data loads quickly, but the page is just waiting for the data to be filtered and for the chart to render. The annotations in the chart are what take so long to render, removing the annotations the chart pops right up.

We have reports that Projections is loading fairly quickly in IE11, despite what I experience on BrowserStack as excruciatingly slow. So maybe Vitals is the same? 

It seems we have a few options here
1. Do nothing and just hope that the vitals page loads more quickly on a real browser than it does on the emulated browsers that I have access to.
2. Put in some skeleton components that will populate when the data/chart is ready
3. Try to figure out a way to change our `isLoading` logic such that it only shows true when the data is filtered and the chart is ready to render. This is going to be pretty tricky and probably time consuming.

@Catacola @soniachokshi Thoughts on how to proceed?
