### ISSUE TITLE
Enable Vitals access for head of ID P&P

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#1345]
**What needs to be done? Why does it need to be done?**
Add bunderwo@idoc.idaho.gov to allowlist for ID vitals. We are meeting him in person Monday 9/27 at 8am PT and he just made a request where it would perfect to give him access to Vitals. "Finally, I need a snapshot of District 7 and how all PPO’s are doing.  Really, just a dashboard for me to see all of the PPO’s case triage in D7.  This is where we are hurting the most in terms of staffing and I need to deploy help – and I want to see which PPO’s are struggling with their workload."

Ideally able to get him access before we meet with him, but not a huge deal if not (I recognize there are 0 working hours before the conversation). I will show him on my laptop and tell him we'll get him set up with access during the week.

**Additional context**
Add any other context about the task here.

**Comment by daschi** [comment]
@sychang I did the following steps this morning:
- Added bunderwo@idoc.idaho.gov to the `recidiviz-123.static_reference_tables.us_id_leadership_users` static table with community_practices set to true, and can_access_leadership_dashboard set to true (false for case triage) so that it'll be included in the dashboard_user_restrictions CSV going forward
- Added them to the `dashboard_user_restrictions` CSV in the bucket so that it would be imported to the database table now and be available for logging in

@Catacola @jovergaag let me know if I missed anything!
