### ISSUE TITLE
Create "Prison population by facility" chart for US_TN Prison page

### ISSUE THREAD

**Issue by jovergaag** [Recidiviz/pulse-dashboard#1417]
**Is your feature request related to a problem? Please describe.**
Create the "Prison population by facility" chart for US_TN Prison page. The metric is already created, `prisonFacilityPopulation`.

[Design](https://www.figma.com/file/Mw6kSEP2jdr9i7UVEjPuCI/UP-Consolidation?node-id=2557%3A8271)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by Catacola** [comment]
@nasaownsky I've created a branch which creates a new metric called `prisonFacilityPopulation` containing the current population by facility called `kesich/1417-create-facility-pop-metric`. There should now also be a fixture file in `gs://recidiviz-staging-dashboard-data-demo/US_TN/` called `prison_population_time_series.json` which will power both the population over time chart and the facility population chart.

If you get to this before the linked PR is merged (#1427), please create your new branch on top of `kesich/1417-create-facility-pop-metric` instead of `main` to use the newly created metric. There is a dummy viz component whoch the new data is already piped to called `VizPopulationSnapshot` which you can modify as much as you like.

**Comment by nasaownsky** [comment]
@Catacola great work! Could you please send me this new fixture file over mail, because I don't have configured `gsutil`. Thanks!
