### ISSUE TITLE
Add color to distinguish negative and positive numbers in map mode for admissions vs. releases

### ISSUE THREAD

**Issue by kbinney** [Recidiviz/pulse-dashboard#170]
**Is your feature request related to a problem? Please describe.**
The `ADMISSIONS VERSUS RELEASES` chart in "map" view does not distinguish between positive and negative numbers. This is confusing to those who want to know which counties have more people being released (negative) and which have more people being admitted (positive)

**Describe the solution you'd like**
Bubbles with positive numbers are in red scale, bubbles with negative numbers are in the current blue scale. The bubble size still conveys the magnitude of the number. 

**Describe alternatives you've considered**

- Transforming the bubble color & size minimum to be relative to most positive number, so the smallest / lightest bubble is the biggest positive number, biggest / darkest bubble is biggest negative number. This option is confusing to user as to why negative gets to be dark and positive is the smallest. This would also be true for a reverse scale form most negative to most positive
- Changing shape or adding shading to indicate positive / negative. This is not as obvious to users at a glance for which elements mean what, and adds an additional "dimensionality" from user perspective to understand. 

**Additional context**
I don't think we currently have a red scale. We would need to develop and, ideally, validate one could distinguish the red scale and blue scale if color blind (though those who are color blind likely wouldn't be worse off with differing pos/neg colors than they are now where the color is the same).

**Comment by jessex** [comment]
@kbinney I tested this out and I think it has a nice effect! Red vs blue helps you tell immediately at a glance if something is negative or positive. One question is for how to define the scale: should the maximum value (from which the darkest shade is derived and thus every other value's shade derived) be just the maximum absolute value across the whole chart, or tracked separately for positive and negative?

The easy thing, which I've already done, is to use the same absolute maximum value for the entire chart. So if your biggest negative value is, say, -50, and your biggest positive value is, say, 10, then in general the negative shades for the chart are going to be darker and the positive shades are going to be relatively lighter, since the maximum value for the entire chart is 50 and all of the positive values will be lower on the scale. The alternative solution, which requires more effort but is doable, would be to keep track of the max positive value and the max negative value and scale positive and negative values to their respective max. So in the example above, the fact that the "max" negative value is much larger than the max positive value would have no impact on the distribution of shades between positive and negative values.

What do you think is preferable from a UX perspective? I can see arguments either way, regardless of engineering effort.

**Comment by kbinney** [comment]
I was thinking have the same maximum value for the whole chart. 

I think that allows you at a glance to try to compare the magnitude of positive and negative numbers to each other, which is nice.
