### ISSUE TITLE
Add officer last names to revocations by officer chart

### ISSUE THREAD

**Issue by kbinney** [Recidiviz/pulse-dashboard#176]
**Is your feature request related to a problem? Please describe.**
Generally, officers in ND only know their own officer ID. Their supervisors don't know how IDs map to names, and it is not particularly easy for them to get that info. 

**Describe the solution you'd like**
Add last names of officers to revocations by officer chart. Instead of Officer 165, have Officer Binney (165)

**Describe alternatives you've considered**
Leaving as is, using officer initials, using officer full names. 

**Additional context**
This isn't high priority, but if low effort would help build on momentum gained by getting program managers access to the dashboard.

**Comment by jessex** [comment]
This one is a little tricky, @kbinney.
- If you just show the full name then the label is long and it consumes a lot of the vertical space of the chart and squishes the actual bar portion
- You can't easily isolate a last name and just display that because sometimes the names will have a suffix or otherwise not fit the format we might expect (i.e. names are hard). And even if this would work most of the time, sometimes you get long last names so this doesn't fully eliminate the squishing
- It might be possible to display just the id along the x-axis and display the name and the id in the tooltip, but I haven't figured out how to do that just yet

What do you think would be the ideal approach here?

**Comment by kbinney** [comment]
Thanks for exploring all those options. 

The problem is that it is hard for individuals to match IDs to officer names. The naive way to make this easier (adding names to charts) seems less than ideal based on info here. ND has a relatively small number of officers, so I'm inclined to see if we can add a way for them to download the Officer ID - officer name mapping from our dashboard to make the matching process easier. (ie like a csv with a column for ids and a column for names). 

I think including this as an export option is non-intuitive. I want to play around with formatting a bit before declaring the ideal position to download that mapping. 

All program managers figured out how to match officer numbers to names by pulling an external report, so I'm actually going to lower the ranking priority of this issue. It was not a great user experience for them to have to pull the outside report to get that information, hence adding this as an issue.

**Comment by jessex** [comment]
@kbinney do you have any new thoughts on this one? We want to make a call as to whether there is engineering work to be done here.

**Comment by kbinney** [comment]
Yes, this is actually in my design backlog. This chart in general is
cramped when all officers are selected, so working with design on different
default view and will include names in that discussion. Will update when I
get a design

**Comment by jessex** [comment]
Got it. This one is blocked for now then, @DmitryJakubovsky.
