### ISSUE TITLE
Prison population over time and prison population by dimension counts don't match

### ISSUE THREAD

**Issue by jovergaag** [Recidiviz/pulse-dashboard#1780]

**Comment by jovergaag** [comment]
https://docs.google.com/document/d/1vdXgI1S5JUcBVQYpkgvIgG0wZ71Ig5NocYHwhuVsFoc/edit#bookmark=id.7colvhnmi7k

**Comment by jovergaag** [comment]
The prison population over time counts also do not match the [external validation sheet](https://docs.google.com/spreadsheets/d/1mRH9SVSC7hPx-D2ZbUx4z7cKAPzxyNsS/edit#gid=1602415050).

**Comment by danawillow** [comment]
I took a look at the population over time vs the list of people as per the doc (by facility actually seems to match the totals). For those two pages, the counts don't match because of filtering out null values.

For the over time query, it happens after all aggregation has happened. So if you have a row with `age=null`, that person will still be included in `age=ALL` counts.

In the list query, it also happens at the end, but since we're operating on individual rows, someone with `age=null` won't be counted.

I actually think this probably used to work, and got broken by https://github.com/Recidiviz/recidiviz-data/pull/11728/files#diff-6ca88c7f2ae5f9e5de98da13b0e5eda703212cb96b490aa970751c6d61622f7a, which caused us to stop displaying values labeled "Unknown".

**Comment by jovergaag** [comment]
Oh thats interesting. I'm thinking that we should actually NOT make the person level views an instance of `PathwaysMetricBigQueryViewBuilder` and make them `MetricBigQueryViewBuilder` instead. We don't want to filter out any rows from these, even if they have some unknown dimension values. Those sweeping filters were applied to reduce the size of the views to remove the dimensional combinations that would be unreachable by the filters.

Can you give that a try and see how the counts end up?

**Comment by danawillow** [comment]
As for the external validation sheet, I put the diffs in a [spreadsheet](https://docs.google.com/spreadsheets/d/1fU-owhnCwLnlUenfMtMd0uA4OQTI6BKgkJ7sF3_uZx4/edit?usp=sharing). There's two categories of diffs:
1. Sites that don't appear on the validation spreadsheet at all. I assume we can ignore these
2. Sites that do! These diffs tend to be off by a small number (some matched exactly, most were off by <5, the highest was off by 11).

I'm going to spot check a few of these and see if I learn anything interesting.

**Comment by danawillow** [comment]
Spot checked 5 IDs, all of which were either missing from the sheet or from our tables- none were categorized as the wrong location. Nothing stood out to me as being particularly interesting about them 🤷‍♀️

**Comment by jovergaag** [comment]
@danawillow Thank you! This is perfect. I went through and added a few notes about the facilities where the counts are the most different. For the most part, it is because they are County Jails which neither TN or Pathways include in their prison population numbers. I think the rest of the differences can be attributed to facilities being renamed. 

Our population seems to only be off by 119 - which is far less than 1% - an error margin that I'm comfortable with!

Thank you for this investigation!

**Comment by jovergaag** [comment]
Oh but wait - dataflow seems to be correct but the pathways views still do not have the correct numbers.

```
select *
from `recidiviz-staging.jovergaag_10641_dashboard_views.prison_population_snapshot_by_dimension`
where state_code='US_TN'
and gender='ALL'
and legal_status='ALL'
and age_group='ALL'
and length_of_stay='ALL'
```

So it must be a problem in the pathways view.

**Comment by jovergaag** [comment]
Out of curiosity - which date were you using for this analysis?

**Comment by danawillow** [comment]
1/1/21
