### ISSUE TITLE
Enable per-user rollout of almost-eligible features

### ISSUE THREAD

**Issue by macfarlandian** [Recidiviz/pulse-dashboard#1941]
**What needs to be done? Why does it need to be done?**
We need to control the rollout of the features in this Epic so that they are accessible to a small group of users for a test period before going into wide release. (We may also want to do a phased rollout of the wide release, though that is TBD.)

There are various plausible ways of accomplishing this: 
- create and manually curate a table of flags in BigQuery that gate the export of almost-eligible data by supervising officer
- manually add the flag to user metadata in Auth0 and use that to turn the feature off on the frontend
- use the `feature-variants` feature from Case Triage to manually curate flags in Cloud Storage, fetch them from the new consolidated backend, and turn the feature off on the frontend
- build a whole new thing for this that we control via the admin panel (may also just be a new iteration of `feature-variants`)

The first option has the benefit of suppressing data that won't actually be used (reducing noise for analysis and limiting pointless bytes downloaded), but ties the feature to the data platform release cycle. The other manual options are equally cumbersome in their own ways (lots of manual JSON editing) but can be updated more freely. Building or revamping a fuller feature-flag system would be the most eng work but could let us add convenience features such as "turn on for everyone" (which requires a code change in any of the current or proposed allowlist-based solutions to remove all of the gating code entirely) or being more flexible about where we apply the gate (e.g. in BQ via a CloudSQL connection or in the application)

**Additional context**
[PRD section](https://docs.google.com/document/d/14bca--FPrZO8HOR8owzvRTS0RMIxXtS9yBTBBORYctc/edit?disco=AAAAaAlMk3k)

**Comment by jovergaag** [comment]
Thanks for putting together this list of options!

`create and manually curate a table of flags in BigQuery that gate the export of almost-eligible data by supervising officer` - This option is closest to what Pathways is using for out beta charts feature flag. We just add a column in the `us_xx_leadership_users` with the beta feature flag which then ends up in the user app metadata. It's not a great strategy and I do not recommend doubling down on this because it requires a migration to add the new feature flag column to the `dashboard_user_restrictions` postgres table.

`manually add the flag to user metadata in Auth0 and use that to turn the feature off on the frontend` - I'm also not a huge fan of this option. It seems like it could be cumbersome to manage in the long run. What if we want to enable the feature for 50 users in TN, thats a lot of manual updating of each user's app metadata.

@Catacola, @danawillow and I chatted a few months ago about what the new auth system could look like ideally. We all agreed that relying on the data platform release cycle/DAG is not ideal and it would be great if we just had a database with permissions that was managed by the admin panel. So, at least as of a few months ago, moving towards auth/permissions/feature flags managed by the admin panel is where I think we should think about heading. That is probably not helpful for you now because none of that migration has happened yet, but trying to move in that direction will probably be the most manageable over time.

**Comment by macfarlandian** [comment]
that is great context @jovergaag thank you! I think building on Case Triage is kind of an in-between step in that it doesn't have any dependencies on the data platform, but is still cumbersome and annoying because it doesn't have a database or management UI. I am leaning that way anyway and if anything this provides more support for that option IMO
