### ISSUE TITLE
Support ND early termination form automation (multi-page support)

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#2071]
Form: https://docs.google.com/document/d/1Pt9FEptyaoOtSo-O2DF1Lx8K20m2RAvr/edit?usp=sharing&ouid=109422495622464047889&rtpof=true&sd=true

A few considerations for design of multi-page forms
- There will be many multi-page forms in the future, so we should design it in a way that accommodates that
- Some multi-page forms will only have one page that needs to be completed (e.g., the first page or the last page)
- Some multi-page forms have multiple pages that need to be completed
- There will be tasks with multiple steps in the future (e.g., 2 separate forms that need to be filled out), in case that helps inform an extensible design.

7/22: Assigning to Sonia for mocks right now, but cc @ohaibbq because I know have some cycles to work on it concurrently

**Comment by soniachokshi** [comment]
@ohaibbq For the ND launch, let's make the left panel and form scroll independently from each other. For ND, this will likely mean that the left panel doesn't scroll (because I think there will be fewer client details than TN). For the form, the two pages will just stack on top of each other, and the user will scroll down.

For the form fields, I noticed that some of them are really small. Instead of expanding the fields to accommodate the text as the user is inputting the text, let's just make the form fields bigger. If the spacing is awkward, I think that's ok. If it's possible to magically fit the spacing on export (ie. removing extra spacing if the field is a lot bigger than the inputted text) that would be awesome, but not necessary at all.

**Comment by ldfielding** [comment]
Example forms now saved [here](https://www.google.com/url?q=https://drive.google.com/drive/folders/1aif1pbHSB5XtwG_rK3heHWRX6isXZZ3r?usp%3Dsharing&sa=D&source=docs&ust=1659113143296506&usg=AOvVaw3QolNnmL3Q473673QwF6An)

**Comment by soniachokshi** [comment]
As discussed in [this Slack thread](https://recidiviz.slack.com/archives/C03NQ132E83/p1659109613690329), I put together some mocks for the ND Early Termination form [here](https://www.figma.com/file/bHFeiTm7TswGqP3AOTYFSa/Workflows-Generalization?node-id=105%3A472), where the blue chunks would be editable. 

In an ideal world...
- The document would be able to be exported as an editable .DOCX so that a document could be sent to and edited by other folks (like the States Attorney).
- The same fields on both pages (like the client's name and Criminal No.) would update on both pages if they're updated in one place.
- The ordered list (a-d) would increment with additional list items similar to a Word doc if the user adds more lines. 

Not sure how much of this is possible... it is a bit of a tricky UX because the form fields are more free text than a structured PDF. I will be out of the office next week, but I'm assigning this ticket to @agronomic in case the UX needs to be reconsidered due to eng constraints.
