### ISSUE TITLE
Add comprehensive unit testing

### ISSUE THREAD

**Issue by jessex** [Recidiviz/pulse-dashboard#25]
There is a single test file, `App.test.js`, but it is commented out. We need unit tests for the following:
* Views
* Components
* Basic logic under `src/`
* Backend API logic

**Comment by jessex** [comment]
As part of this, we want to reenable/fix the Coveralls code coverage integration and ensure we get a coverage report with each local build and on each pull request.

**Comment by jessex** [comment]
@Wmaileq, we'd like to continue to make improvements in our test coverage. Here are a few things to tackle next:
- Add unit tests for the backend, i.e. the code under `/server`
- Enable Coveralls for the repository so we get test coverage reports with our build
- Fill in some missing test coverage on the frontend, including `/src/utils/authentication`, `/src/auth0/hooks`, and `/src/auth0/rules`

We can do those three first with separate pull requests. If we make it through those, my next target for improved testing would be `/src/components` but let's see how quickly those first three go.

**Comment by jessex** [comment]
@Wmaileq, I think at this point, you should take a look at the Coveralls report and target any areas that can be high-value additions of test coverage, i.e. high improvements in coverage for relatively less effort.

**Comment by jovergaag** [comment]
@Wmaileq Let's also re-enable the `App.test.js`

**Comment by jovergaag** [comment]
@Wmaileq Since we have so much code churning right now, please prioritize this issue over your other refactor issues (other than the open PRs) for now. We are launching the product to the PA folks on Thursday so I think we should focus on adding test coverage instead of new features/refactors for the next few days to allow any bug fixes and fast follows from that launch to roll through quickly.

`TenantRoutes` would be a great place to start.

Thanks you!

**Comment by Wmaileq** [comment]
Working on `src/react-auth0-spa.js`

**Comment by ageiduschek** [comment]
Closing this! Going to open new issues as test needs arise
