### ISSUE TITLE
Update fixture data across the dashboard

### ISSUE THREAD

**Issue by DmitryJakubovsky** [Recidiviz/pulse-dashboard#317]
**What needs to be done**
Update all fixture data used in demo mode across the dashboard. It's out of date by a few months. Make sure there are no missing columns or values that need to be included for any charts that have been recently updated.

**Comment by jessex** [comment]
@DmitryJakubovsky thanks for filing this, but I am guessing by "Filter is not applied to table" you mean that the table becomes empty in these cases, right? And this is happening while running in demo mode, right? If so, this is because the fixture data for the caseload table in demo mode does not include those districts. It's not a code bug but a fixture data issue.

Once you confirm those quick questions above, I'll update this issue to be a more general "update the fixture data for completeness" task.

**Comment by jessex** [comment]
Pinging @DmitryJakubovsky. Let me know what you think in response to my previous comment.

**Comment by DmitryJakubovsky** [comment]
Sorry for waiting. You are right, it was demo mode. It would be much easier if fixtures would be as similar to real data as possible.

**Comment by jessex** [comment]
Agreed. It's a struggle to keep them up to date because the dimensional explosion modeled by the data is challenging to maintain, much less keep realistic. Given that we know that at the very least the fixture data is now lagging by a few months, I'll pivot this issue to a general "update the fixture data" ticket.

**Comment by jovergaag** [comment]
@jessex Can I close this issue? It seems a bit stale.

I have a new issue open for the most recent round of updated fixture files that includes the new schema details.

**Comment by jessex** [comment]
Yes, definitely!
