### ISSUE TITLE
[Lantern] Add a "state average” line to the “revocations by district chart” showing revocation rates.

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#336]
**Is your feature request related to a problem? Please describe.**
For the revocations by district chart, there is currently no easy way to see the revocation rate for the state overall, and no way for districts to easily see if they are above or below the state-wide rate.

**Describe the solution you'd like**
Add a horizontal black line across the chart to represent the state-wide revocation rate so districts can easily compare whether they are above or below the overall state rate. Like the rest of the chart, this rate would be filtered by the same criteria the user has selected.

The line should be labelled with the rate to 2 decimal places, "State-wide rate = XX.XX%" on the right-hand side of the chart above the line (to decrease the likelihood of interfering visually with any bars) and be the same font size and color as the axis labels.

![image](https://user-images.githubusercontent.com/6633887/81890999-ef2e0a80-956c-11ea-85d6-e6c69db7e514.png)

**Describe alternatives you've considered**
1. Add another bar into the chart representing "overall" revocation rate for the state that would be visually distinct from the other bars but ordinally ordered with the other bars. 
2. Add another bar into the chart representing "overall" revocation rate for the state that would be placed at the _far right_ of the chart so as to not interfere with the ordinal ranking of the other bars.

**Additional context**

**Comment by jessex** [comment]
@sychang, @DmitryJakubovsky has built this and it appears to be working as expected! Two clarifying questions:
1. Should this only be shown in the "rate" mode of the chart, or also in the "count" mode? As currently implemented, it's visible in both. Would not be hard to restrict it only to rate mode, though.
2. You don't want any labeling or hover behavior that shows what the average value actually is, right? The mocks and description don't indicate any such thing but want to be sure.

**Comment by sychang** [comment]
1. This should only be shown in rate mode
2. Double-checked with folks and we'd like to show the actual statewide rate in the label to 2 decimal places, so it might say something like "Statewide rate: 35.12%"

One quick clarification that your second question reminded me of - this line should be showing the revocation rate for the entire state, _not_ the average of each district's rate. I noticed some potential ambiguity in the original thread so I wanted to double check here - apologies if there was any confusion caused.

**Comment by jessex** [comment]
For item 2, that was not our interpretation so we did it as an average of the district bars in the given chart. Are you saying that you want state-wide calculations of revocation rate for all toggle states that a user can select in the app? If so, that means that part of the work that was done so far will need to be changed. It also means that we will need a calculation change to ensure that the `revocations_matrix_supervision_distribution_by_district` view includes `district=ALL` rows in the file.

Once that calc change is made, we will be able to change the logic that computes the average value to look for the rows in the `revocations_matrix_distribution_by_district` and `revocations_matrix_supervision_distribution_by_district` API responses that have all of the identified toggle states (e.g. the right metric_period_months, the right supervision_type, and the right charge_category) but have district=ALL. Those will represent the numerator and denominator values for the state-wide revocation rate from which we will draw the line.

CC @DmitryJakubovsky. I will try to update the fixture file you use in demo mode so that you can go ahead and update the chart logic, but then we won't be able to actually release this to prod until the calc support has been done on our side. Also, note Serena's other, smaller point that the average line should only be shown in rate mode.

**Comment by sychang** [comment]
Yes - confirmed that's the case. Apologies again on my error, I'll update the original issue to clarify.

**Comment by jessex** [comment]
@DmitryJakubovsky hold tight on this one for now--spoke offline with @sychang and she wants to confirm the desired functionality with our partner before continuing.

**Comment by sychang** [comment]
Thanks for the patience! Confirmed the following with our partner: 
- The state-wide rate _should_ update with all toggle states 
- To keep the meaning of the line clear regardless of user state, we'll simplify the copy to say “Overall: XX.XX%”

**Comment by jessex** [comment]
@DmitryJakubovsky, I have pushed a commit to your branch which adds new entries to the `revocations_matrix_supervision_distribution_by_district.json` fixture file with values of district=ALL. This should support the new logic that has been requested for computing the state average:
* For a given combination of filter states, search `revocations_matrix_distribution_by_district` to get the row that features that combination of filters _and_ has district=ALL. That's the numerator.
* For a given combination of filter states, search `revocations_matrix_supervision_distribution_by_district` to get the row that features that saem combination of filters _and_ has district=ALL. That's the denominator.
* Divide them to get the state average revocation rate. This is where we draw the line on the chart.

You could either compute the state average on demand, i.e. whenever a filter is changed, or you could proactively create a map with all of the possible filter combinations that has the pre-computed state average values. It's probably a fair bit simpler to do the first one, on demand, but if it introduces any visible lag then we'd prefer to do the pre-computed approach.

So that's the first thing to change. The second thing to change is to make it so we only display the average when the chart is in rates mode, not in counts mode. The third and final thing to change is to make the text for the annotation line match the format that @sychang posted in her most recent comment: "Overall: XX.XX%" with that number of decimal points. 

You should be unblocked to continue on your PR now. Thanks for the patience!
