### ISSUE TITLE
Update "Case Types" in PA Admissions Plot

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#432]
**Is your feature request related to a problem? Please describe.**
PA has different Case Types than MO, so we need to update the dropdown filter to correspond to the relevant PA types.

**Describe the solution you'd like**
The options in the "Case Type" filter should be the following for PA:

- All
- General
- Sex Offenders
- Domestic Violence
- Mental Health
- AOD 

**Describe alternatives you've considered**
"Street crimes" is another case type PA wanted to include, but they don't believe this information is standardized anywhere in the schema. They think it may exist in case notes somewhere, which would be difficult for us to work with immediately, so it is out of scope.

Special probation cases are supervised by the DOC, but they don’t have a lot of discretion over because they’re determined by the court. Further data investigation is needed to know if this is feasible to include.

**Additional context**
8/20/20 edit: Removing special probation from this list, it will be relocated to a new dropdown.

**Comment by jessex** [comment]
@DmitryJakubovsky: the main thing here is that for PA and for MO, we want the case type filter to be capable of holding separate values, which is a pretty straight-forward change, and we want PA's dropdown to have the ordered list in the description. The only thing that I would like to note here is that we should _not_ add all of these case types to the existing fixture files for the revocation matrix. We can just add these as possible drop-down values while recognizing that, for now, the fixture data will not have complete coverage (since there are no data points yet for AOD or Special Probation).

Given that different states are going to have slightly different data ranges for the same views going forward though, it does mean that in the medium- to long-term, we may want to look into alternate fixture files for different states. But we don't need to worry about that here, just yet, I don't think.
