### ISSUE TITLE
[Core] Report of internal dashboard not loading in ND

### ISSUE THREAD

**Issue by kbinney** [Recidiviz/pulse-dashboard#456]
**Describe the bug**
Pat reports as of the morning of 8/24, the internal dashboard will not load for him. He's blocked on page load.

**To Reproduce**
I could not reproduce the behavior

**Expected behavior**
The page should load, and Pat should be directed to log in. 

**Additional context**
If relevant, there is no record of a visitor from ND in user analytics for today.

**Comment by jessex** [comment]
@kbinney, I think we would need more information to properly investigate this. What URL was Pat trying to visit, what browser/OS is he using, what did he see when he tried to load the page (screenshot if possible)? Is this still happening to him?

**Comment by kbinney** [comment]
This is still occurring. Waiting to hear on URL & browser being used, but received a screenshot today. 
![SnipImage](https://user-images.githubusercontent.com/19810267/92136586-30774e00-edda-11ea-8f97-d7e35b326133.JPG)

**Comment by kbinney** [comment]
This appears to be caused by a bad URL, as user could log in at dashboard.recidiviz.org. 

Below is what the user was trying to use to login with, a link that had previously worked for him. 
URL:  https://login.recidiviz.org/u/login
Brower:  Chrome
Computer:  Dell Laptop

**Comment by jessex** [comment]
Yes I soon as I saw your screenshot I was about to comment. That URL actually _never_ worked for the user: it's a security feature from Auth0 that going straight to the login URL like that does not work. You _have_ to go through the login link on dashboard.recidiviz.org in order to ensure a session gets properly instantiated (see the very long `state` query parameter that gets added to the login.recidiviz.org URL after you click the login link). They may just believe that the login URL worked for them because they have seen it in their browser bar _after_ having clicked on the login link, or after having been redirected to it.

We should improve user documentation to note that you have to log in by going through dashboard.recidiviz.org and that navigating directly to login.recidiviz.org will not work. We should also make sure we are gathering this information as soon as we get bug reports, because we would have identified the cause here immediately.
