### ISSUE TITLE
[Data Complexity] Phase 1 Follow-up: Use optimized format consistently across client-side

### ISSUE THREAD

**Issue by jessex** [Recidiviz/pulse-dashboard#480]
**Is your feature request related to a problem? Please describe.**
As part of our work to increase app scalability in the face of increasing data complexity and volume, we switched the backend to using a new optimized metric file format provided by the data platform. It is working well in production so far!

However, as some in-progress PRs can attest, and as our design document predicted would eventually happen, we are seeing that new features adding on still more dimensionality to certain metrics are causing the client to bog down and even fail to load on machines with lower memory. This is because the frontend is taking the optimized format and immediately expanding back into the previous, wasteful format. This was done simply to make the change simpler and faster, but we should now go a step further and change the frontend to filter on and present from the optimized format itself.

**Describe the solution you'd like**
Update the client side code in `src/api/metrics`, and calling code in chart components, to work directly with the optimized format. This should put a nice damper on memory consumption on the client and because the optimized format is just arrays and arithmetic, filtering data points should seemingly be even faster because we'll be able to perform constant time lookups instead of linear scans with each new filter interaction.

We should never expand the optimized format into the non-optimized format, but the one chart that still uses the non-optimized format (the Revocation Analysis Caseload Table) should continue unchanged.

**Describe alternatives you've considered**
N/A. This is the alternative to _not_ doing this work in #464.

**Additional context**
See the original data complexity design doc for more information on the implementation.

**Comment by ageiduschek** [comment]
Done, ready to merge, not merging before PA launch.

**Comment by jovergaag** [comment]
Update on this. After merging master yesterday I was doing some performance analysis and more QA and ended up finding a few bugs. Two were easy-ish to fix - but another bug in the filtering ended up being very difficult to get to the root of because of the added complexity of the optimized format data being passed through the filters. This is added layer of complexity over the filtering logic was the primary reason I suggested not to merge this before PA launch - and I'm even more nervous about it now given my difficulty debugging yesterday. It turns out it was a bug in the metadata.dimension_manifest of one of the metric files. filterOptimizedDataFormat is using the dimension_manifest and value_keys differently than expandMetricRepresentation so the expanded data vs unflattenened data had different filtering results.

Given all this, I'm inclined to again suggest holding off on merging this to see if we can improve IE11 performance by optimizing the data itself.

**Comment by ageiduschek** [comment]
Ready to go, blocked on deploy of v1.28
