### ISSUE TITLE
Update PA risk chart with PA-specific categories

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#491]
**What needs to be done? Why does it need to be done?**
PA has different risk level categories than MO. The risk level chart on the revocations matrix needs to be updated to reflect that. Charts that need to be updated
- Risk level chart
- Race chart
- Gender chart

The Risk Level column in the "Admitted individuals" list at the bottom should also reflect this state-specific mapping (show MEDIUM instead of MODERATE for PA).

**Additional context**
Add any other context about the task here.

**Comment by jjdressel11** [comment]
More context!

MO's risk assessments have 4 risk level categories: Low, Moderate, High, Very High. The Lantern UI is currently built to support the following categories:

- Not Assessed
- Low Risk
- Moderate Risk
- High Risk
- Very High Risk

We need to update the Lantern FE for PA to have the following risk level categories:
- Not Assessed
- Low Risk
- Medium Risk
- High Risk

The following charts have to be updated:
- Risk level chart
- Race chart
- Gender chart

The Risk Level column in the "Admitted individuals" list at the bottom should also reflect this state-specific mapping (show MEDIUM instead of MODERATE for PA).

**Comment by jovergaag** [comment]
@sychang @jjdressel11 

Question on the data labels here. We have different data labels for the Risk Level chart than for the Gender and Race chart. Do we want to standardize data labels across the charts or was this intentional? Risk Level chart does not have the word 'Risk` in the label.

![Screen Shot 2020-09-28 at 3.25.28 PM.png](https://images.zenhubusercontent.com/5f68f900f5589b314e6a6ec3/8a26880f-9eeb-4436-bc39-d83bb36d6878)
![Screen Shot 2020-09-28 at 3.25.18 PM.png](https://images.zenhubusercontent.com/5f68f900f5589b314e6a6ec3/d11d8b80-8235-49bc-8885-b0cd09ec841b)
![Screen Shot 2020-09-28 at 3.25.08 PM.png](https://images.zenhubusercontent.com/5f68f900f5589b314e6a6ec3/19e8d250-3220-4f36-bb0e-2553fde5c0b9)

**Comment by jovergaag** [comment]
Another question: do we want to add an 'Overall' column on the Risk Level chart to be consistent with the Gender/Race charts?

**Comment by jjdressel11** [comment]
I assume these decisions were intentional (aka leave labels as is) but I will defer to @sychang here!

**Comment by sychang** [comment]
Chatted offline with Jen but replying here for posterity:
- Updating the text labels on the risk level and caseload table to "low risk" as opposed to "low"
- Leaving everything else as is: no 'Overall' column and no updates to the race and gender charts since those may be subsumed longer term by race/gender re-visualizations.
