### ISSUE TITLE
Authentication is broken in IE11

### ISSUE THREAD

**Issue by jovergaag** [Recidiviz/pulse-dashboard#548]
**Describe the bug**
Whether deployed to staging, local dev, or served locally by firebase, authentication requests from IE11 are not reaching Auth0. Auth works fine in other browsers.

**To Reproduce**
1. Try to open the dashboard from IE11.
2. Notice that nothing on the page loads. 

**Expected behavior**
Successful authentication and dashboard page load on IE11.

**Screenshots**
Screenshots revealing sensitive information _must not_ be shared. If a screenshot is helpful in diagnosing and resolving the bug, please send this directly to a contact on the Recidiviz team.

**Desktop (please complete the following information):**
 - OS [e.g. Windows 10]: 
 - Browser [e.g. chrome, edge]: 
 - Version [e.g. 22]: 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]: 
 - OS: [e.g. iOS8.1]: 
 - Browser [e.g. stock browser, safari]: 
 - Version [e.g. 22]: 

**Additional context**

**Comment by jessex** [comment]
Without knowing anymore about the actual issue, it would be unsurprising if this were caused by the the [Auth0 dependency upgrade](https://github.com/Recidiviz/pulse-dashboard/commit/4f77aee565f09b52f94223446d51e2da57667472#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) from October 1st.

Has this issue reached production, @jovergaag?
