### ISSUE TITLE
Change district numbers to number - name

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#592]
**What needs to be done? Why does it need to be done?**
During the PA training, PA flagged that they discuss districts in terms of names, rather than numbers. This task involves updating the following district numbers on the PA dashboard to include both district numbers and names. They should be assigned as follows: 
- 01 - Philadelphia
- 02 - Pittsburgh
- 03 - Harrisburg
- 04 - Scranton
- 05 - Williamsport
- 06 - Erie
- 07 - Allentown
- 08 - Mercer
- 09 - Altoona
- 10 - Chester
- CO (no change)

**Additional context**
There is a separate, related, task to add sub offices into the district filter.

**Comment by jovergaag** [comment]
@ageiduschek Can you please add some detail here about the schema changes that will contain these number/name mappings once you finalize it today. I will add it to the fixture data and assign this to @Wmaileq once we have that detail.

**Comment by jovergaag** [comment]
For this district number -> name mapping, will we be using the district name everywhere instead of the number? This would meanin the filter, as well as labels in all of the charts?

One place where I think the labels will get a little busy is if we were to use the district name in the X-axis labels of the Officer Chart. So a label there would be: `Williamsport-John Smith` instead of `05-John Smith`

@sychang

**Comment by sychang** [comment]
One thing we had discussed was including both name and number of the form "name - number" in the district filter and then only using the number on the officer chart - would that be workable for the officer chart? So that the x-axis can still say 05-John Smith, and it would be clear what 05 is because the district filter would say "05 - district name"

**Comment by sychang** [comment]
Adding dependency so we add suboffices to the district dropdown before we make this change.

**Comment by jovergaag** [comment]
I think this should actually be a blocker for the sub-offices issue rather than the reverse (current). We can do this work first, which will fetch the id -> name mapping file, and add the district name to the filter. The sub-offices will just be an extension of that.

**Comment by jovergaag** [comment]
@sychang I had originally asked this question in 714 but since I re-ordered them, I'll ask it here also.

Some of the location names are slightly different than what you noted above. For example, the metric file lists "Pittsburgh D.O." Instead of "Pittsburgh" for district 02.  What is the naming convention that you would prefer here? It also lists "Central Office" instead of CO. Do we want to spell that out?

Re your question about whether we can include the district number instead of name in the axis labels on the officer chart: yes! We have an issue for that here:[ #4612](https://app.zenhub.com/workspaces/-lantern--5f2cdf04d4d9670013da86ed/issues/recidiviz/recidiviz-data/4612)

Do we want to display the district number or district name in the district chart?

**Comment by sychang** [comment]
Looks like there an open question here of how to figure out which level_1 sites actually comprise suboffices. I started trying to aggregate and map them here: https://docs.google.com/spreadsheets/d/1CUxRYgb4srUHsjVAN924ChITa7gCkJNa1vyhJEi0kNY/edit?usp=sharing

Most of them are straightforward, but there are about 10% that I don't know how to map just by eyeballing them. To revisit tomorrow!

**Comment by jovergaag** [comment]
@sychang Once we have the complete mapping, lets open a recidiviz-data issue to aggregate in the view as well as format the district/sub-office names the way we would like them to be displayed ex: remove the "D.O.".  This issue will be dependent on that.
