### ISSUE TITLE
Prevent auth0 email verification errors from occurring

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#594]
**What needs to be done? Why does it need to be done?**
When PA was creating accounts for the 10/29 training, all of them ran into the same issue in which when they clicked the link to verify their emails, it took them to an error page saying "email could not be verified." However, that error message was sent erroneously because they had actually all successfully created accounts and were able to log in. 

I believe this is an issue on auth0's end when we enable the email verification feature. See: https://community.auth0.com/t/your-email-address-could-not-be-verified-page/34593/3

This task is to look into how we may be able to prevent the issue from occurring on our end, despite it being an auth0 bug. There appear to be a workaround we can implement on our end: https://community.auth0.com/t/email-verification-link-works-but-shows-error-page/32409/12. 

**Additional context**
Here are the instructions we gave PA on how to create accounts: https://docs.google.com/document/d/1iuojdgRnHGTuFDiSla_nuZbM-6KvoeHP88WIjexBktU/edit

I don't think this is browser specific because everyone had issues, including Bret who was most likely using Chrome.

Dropping into 11/2 for visibility but this is not beta exit blocking, and Jen to prioritize with the rest.

**Comment by jovergaag** [comment]
@sychang While debugging another auth bug today, I did quite a bit of testing with this and was not able to reproduce. Everything that I could find pointed toward this behavior being due to an Auth0 bug. I'm inclined to say that they fixed the bug.

I tested this ~20 times. In both staging and production, on Chrome, Firefox, as well as IE11 and clicking through the email verification link was successful each time.

I'm trying to think through something else environmental that would have caused this but can't think of anything. The only difference is the @recidiviz.org email vs a PA gov email but there is nothing in the email verification rule that cares about the email address.

Should we close this or would you like to have someone from CSG or PA perform a test signup for us?

**Comment by sychang** [comment]
Thank you for doing so much digging into this one! Let's go ahead and close this and we can make sure to test it first with a small group of PA supervisors when we distribute the dashboard to a broader group in PA to make sure there's no issue.
