### ISSUE TITLE
[MO District Restricted View] Decide: use Auth0 rule or do pseudo-auth with email list sent to front end

### ISSUE THREAD

**Issue by ageiduschek** [Recidiviz/pulse-dashboard#669]
**What needs to be done? Why does it need to be done?**
We need to somehow get information to the frontend about the districts (level_1_supervision_locations) that MO district supervisors can view data for. This task encompasses the design work to decide the best out of these options:

1) Query an api.recidiviz.org endpoint that will serve the email list inside of an Auth0 rule and update the userMetadata inside that rule with a list of allowed districts ([example](https://community.auth0.com/t/how-do-i-call-my-api-from-a-rule/41309/2) that queries an API).
2) Query for the file directly from the frontend and wait to show other data until we have the results and know whether we need to restrict the view.

**Additional context**
Josh weighed in on his opinion on this decision here: https://github.com/Recidiviz/recidiviz-data/issues/4733#issuecomment-735579936

**Comment by jovergaag** [comment]
After thinking about this for a while, I'm in agreement with Josh (in a comment in #[4733](https://github.com/Recidiviz/recidiviz-data/issues/4733#issuecomment-735579936)) that the best way forward here is to send the district mapping directly to the FE and allow the FE to then set the district filters accordingly based on a user lookup within that file.

The other route, creating a field in the Auth0 user metadata would require an [API call from a rule](https://community.auth0.com/t/how-do-i-call-my-api-from-a-rule/41309). Even if the rule was last in line, it would still run on every successful authentication. Performance wise, adding the user mapping API call to run in parallel with fetching the other metrics to the FE, rather than adding in line serially as a part of the auth is the fastest. 

Auth0 rules run on silent-auth as well as during the full auth flow, so once the mapping file hits the API, whether it is sent directly to the FE or to Auth0 as part of a silent-auth, a new user's list of restricted districts will update the same. In other words - neither method will prevent or contribute to a stale mapping more than the other as far as I can tell.

I say lets go forward with sending the mapping directly to the FE.

cc: @jessex

**Comment by ageiduschek** [comment]
It has been decided to just do pseudo-auth
