### ISSUE TITLE
Update PA district dropdown to include nested sub-offices

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#714]
**What needs to be done? Why does it need to be done?**
The district dropdown on the current Pennsylvania dashboard only shows numbered districts, like so:

![image.png](https://images.zenhubusercontent.com/5ec1f17e7e863d6fd9e7e91c/585ed161-a1ff-4657-be68-9883fe090ae5)

This task is to updated the district dropdown to contain nested sub-offices. This dropdown should have identical behavior to the nested admission type filter #423. Note, the mock is outdated and the ID should be pre-pended to the sub office name, to say "01 - Countywide" rather than only "Countywide"

![image.png](https://images.zenhubusercontent.com/5ec1f17e7e863d6fd9e7e91c/4cdd804f-ac98-4144-91f3-a2d3269a81c6)

The districts and nested (indented) sub office are as follows:

01 - Philadelphia
- Countywide
- Northeast
- Northwest
- Specialized
- West

02 - Pittsburgh
- Greensburg
- North Shore
- Pittsburgh DO

03 - Harrisburg
- Harrisburg DO
- Lancaster
- York

04 - Scranton
- Scranton DO

05 - Williamsport
- Williamsport DO

06 - Erie
- Erie DO

07 - Allentown
- Allentown DO
- Reading
- Wernersville

08 - Mercer
- Butler
- Franklin
- Mercer DO

09 - Altoona
- Altoona DO

10 - Chester
- Chester DO
- Norristown

CO

@jovergaag if there is any dependency on converting numbers to names, feel free to add! 

**Additional context**
This should only be done for Pennsylvania. No changes to Missouri dashboard.

**Comment by jovergaag** [comment]
@sychang I'm looking at the `supervision_locatiuon_ids_to_names` file in the metrics bucket. A couple of questions:

1. Some of the location names are slightly different than what you noted above. For example, the metric file lists "Pittsburgh D.O." Instead of "Pittsburgh" for the level_2 (regional) district name. Then it lists "PITTSBURGH DISTRICT OFFICE" instead of "Pittsburgh DO" for the sub-office. What is the naming convention that you would prefer here? 
2. Do you want all of the names titlecase?
2. The mapping file also lists several sub-offices that are not in your list above. For example: "BEAVER FALLS GENERAL UNIT" under "Pittsburgh D.O."  Do we want to allow all of these suboffice to be visible in the filter? I'm guessing that these sub-offices that are missing from your list above just don't have any revocations that show up in the dashboard. So if we do include it in the filter, selecting that district would show 0 revocations on the dashboard. Is that the intended behavior?

Is this mapping file not ready for prime-time yet? We can always include the static list that you included above if the mapping from the pipeline still needs some fine tuning...let me know what you want to do.

**Comment by sychang** [comment]
1. Are all the level_2 district names in the form "XXX D.O."? If that's the case and it's fairly easy to truncate away the "D.O." then let's truncate it to match "Pittsburgh." If not particularly easy, "Pittsburgh D.O" (what's in the metric file is fine). For sub-office, fine to leave as "Pittsburgh District Office" but let's titlecase.
2. Yes, titlecase
3. Hmm I can see them not showing up either because those suboffices are now inactive or my list is wrong. Do you have a list of all that are not on my list? I can run them by PA to double check. If they are active suboffices, let's include them in the filter. But if those suboffices don't exist anymore, then we would keep them off. My list was based off the reports that their leadership receives.

**Comment by sychang** [comment]
Is mapping file ready question for me or @ageiduschek ? I don't know the current state of the mapping file but lmk what you need from me!

**Comment by jovergaag** [comment]
@sychang Yes, all the level_2 names are "XXX D.O".  If we don't want to include the "D.O", lets do that formatting in the view so that the FE doesn't have to truncate the D.O. Issue: #5505

The sub-office names are in this [file](https://console.cloud.google.com/storage/browser/_details/recidiviz-staging-dashboard-data/US_PA/supervision_location_ids_to_names.json?organizationId=448885369991&project=recidiviz-staging), lmk if you don't have access.

I'm not sure who the mapping file is ready question is for. Maybe @ageiduschek. Should I use that file for the mappings or is it stale?

**Comment by jovergaag** [comment]
@ageiduschek Another related question, how easy would it be to get a dataset that has the `level_1_supervision_location` enabled for all of the dashboard views? There are 168 sub-offices in the `supervision_location_ids_to_names.json` and I'm spending a lot of time trying to update the fixtures so that they have the level_1/level_2 values that make sense and have a nice spread of data for the filter development/testing in demo mode. If that is something that would be quick, maybe I'll hold off manually updating these fixtures...

**Comment by ageiduschek** [comment]
@jovergaag I think if you follow the instructions in the two places with `TODO(#4524)` you will get level_1_supervision_location, if you just want to do that to the views locally and get some good fixture data from a sandbox views dataset.

I also don't know what you're talking about with the mapping file @sychang.

I can make that view change to strip D.O., just let me know.

**Comment by jovergaag** [comment]
@sychang I saw the email go back and forth a few times about the suboffice mapping. Is that finalized? 

As soon as it is, can you please open a recidiviz-data issue to aggregate those sub-offices, that means creating new  level_1_supervision_location ids for each aggregation, maybe it would become a `level_1_supervision_location_internal_id`? The same issue can format the names to be what we want displayed on the FE.

This issue, as well as creating fixtures to support this issue, will be blocked by that data issue.

**Comment by sychang** [comment]
Chatted with @ageiduschek offline and for this particular situation, we will replace the current level_1 unit-level data with the correct sub office data (rather than aggregating, or creating a new level). Will file a ticket for that now! The schema for the fixture files shouldn't need to change in that case, but Anna to confirm.
